# Generated by Django 4.2.7 on 2025-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
